# Generated by Django 4.2.3 on 2023-07-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_userprofile_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='created_date')),
                ('username', models.CharField(blank=True, default='', max_length=254, verbose_name='name')),
                ('password', models.CharField(blank=True, default='', max_length=254, verbose_name='name')),
                ('profile_img', models.ImageField(blank=True, default='{% get_media_prefix %}images/logo/blank_profile_image.png', upload_to='profile_img', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Login Settings',
                'verbose_name_plural': 'Login Settings',
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
