# Generated by Django 4.2.3 on 2023-07-30 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_login_user_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login_User',
        ),
    ]
